### ISSUE TITLE
Responsive top bar

### ISSUE THREAD

**Issue by RomanenkoVladimir** [MaibornWolff/codecharta#1423] opened 2020-10-23 11:46 UTC
# Feature request

- CodeCharta visualization is responsive, scaling to the screen size and behaving as expected on smaller screens.
- However, the top bar features set heights and widths making it difficult to use on smaller windows, with some feature like edge settings being unreachable. 
- The size for components like the blacklist or the flattenend list might also be an issue in such cases.

Making the website responsive for smaller devices, e.g. Pads and Phones might improve user experience and increase usability.

WDYT?

**Comment by BridgeAR** [comment] 2020-12-24 17:06
This is a duplicate of #1037

**Closed by BridgeAR** 2020-12-24 17:06 UTC
Labels: feature, javascript, pr-visualization, priority:medium
