### ISSUE TITLE
No files loaded when closing the dialog window

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#875] opened 2020-03-11 15:06 UTC
# Bug

## Expected Behavior
When I have a map loaded and open the dialog to load a new file and close it again, I expect that nothing changes at all. The application should return to it's state before I opened the dialog.

## Actual Behavior
When I have a map loaded and open the dialog to load a new file and close it again, the file selection vanishes and I can't select another loaded file until I load a complete new file.

## Screenshots

![no_file_selected](https://user-images.githubusercontent.com/12533626/76431558-05bfb600-63b2-11ea-9426-054cccbd3ae0.gif)

## Additional Info
This somehow only happens with maps that were loaded through the dialog. It doesn't happen with the default loaded maps.

## Steps to Reproduce the Problem
  1. Open any map
  2. Open the "load file dialog"
  3. Close it again

## Specifications
  - CodeCharta Version: master
  - OS: macOS
  - Browser: Chrome

**Comment by alschmut** [comment] 2020-03-11 15:23
I saw that the other day as well and committed a [fix](https://github.com/MaibornWolff/codecharta/pull/860/commits/71755064ca4013c6f14fd1bc9ef45ef57be48af2) on the other file validation branch ✌️

**Comment by alschmut** [comment] 2020-05-28 12:30
The above mentioned fix, doesn't fix the issue correctly. I undid the change again on the other branch some time ago.

How to solve this bug:
- call `codeChartaService.loadFiles(nameDataPairs: NameDataPair[])` with all files inside that array
- loop over every file (NameDataPair) and validate it
- WHEN at least one file was valid THEN reset the `state.files`

The problem is:
- The `fileChooser.component.ts` calls the function `codeChartaService.loadFiles(nameDataPairs: NameDataPair[])` for every imported file, instead of once with all files. As the fileChooser is a legacy angularJS directive, I was not able to change the code in there to make it work.

**Comment by NearW** [comment] 2020-07-03 09:37
@JaiJoPa collecting multiples before setting them all

```ts
export class FileChooserController {
	private files : NameDataPair[] = []

	/* @ngInject */
	constructor(
		private $scope,
		private dialogService: DialogService,
		private codeChartaService: CodeChartaService,
		private storeService: StoreService
	) {}

	public onImportNewFiles(element) {
		this.$scope.$apply(() => {
			this.storeService.dispatch(resetFiles())
			let content
			let readFiles = 0

			for (const file of element.files) {
				const isCompressed = file.name.endsWith(".gz")
				const reader = new FileReader()
				reader.onloadstart = () => {
					this.storeService.dispatch(setIsLoadingFile(true))
				}
				reader.onload = event => {
					if (isCompressed) {
						const zlib = require("zlib")

						content = zlib.unzipSync(Buffer.from((<any>event.target).result))
					} else {
						content = (<any>event.target).result
					}

				}
				reader.onloadend = () => {
					readFiles++
					this.addNameDataPair(file.name, content)
					console.log("adding ", file.name)

					if(readFiles === element.files.length) {
						this.setNewData()
						console.log("setting files")
					}
				}
				isCompressed ? reader.readAsArrayBuffer(file) : reader.readAsText(file, "UTF-8")
			}
		})
	}

	public setNewData() {
		this.codeChartaService.loadFiles(this.files).catch((validationResult: CCValidationResult) => {
			this.storeService.dispatch(setIsLoadingFile(false))
			this.printErrors(validationResult)
		})
		this.files = []
	}

	private addNameDataPair(fileName: string, content: string) {
		this.files.push({
			fileName,
			content: FileChooserController.getParsedContent(content)
		})
	}
}

```

**Closed** 2020-07-23 14:01 UTC
Labels: bug, pr-visualization
