### ISSUE TITLE
Out of memory exception for the git log parser where the repository has a lot of movement/renaming

### ISSUE THREAD

**Issue by MO2k4** [MaibornWolff/codecharta#3394] opened 2023-11-03 12:41 UTC
# Bug

## Expected Behavior

The git log parser should succeed in reading the git log.

## Actual Behavior

```
at de.maibornwolff.codecharta.importer.gitlogparser.converter.ProjectConverter.addRootToEdgePaths(ProjectConverter.kt:48)
at de.maibornwolff.codecharta.importer.gitlogparser.converter.ProjectConverter.addVersionControlledFile(ProjectConverter.kt:32)
at de.maibornwolff.codecharta.importer.gitlogparser.converter.ProjectConverter.convert(ProjectConverter.kt:68)
at de.maibornwolff.codecharta.importer.gitlogparser.GitLogProjectCreator.parse(GitLogProjectCreator.kt:26)
at de.maibornwolff.codecharta.importer.gitlogparser.GitLogParser.createProjectFromLog(GitLogParser.kt:128)
at de.maibornwolff.codecharta.importer.gitlogparser.GitLogParser.buildProject$GitLogParser(GitLogParser.kt:82)
at de.maibornwolff.codecharta.importer.gitlogparser.subcommands.LogScanCommand.call(LogScanCommand.kt:60)
at de.maibornwolff.codecharta.importer.gitlogparser.subcommands.LogScanCommand.call(LogScanCommand.kt:11)
at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
at picocli.CommandLine.access$1500(CommandLine.java:148)
at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2536)
at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2538)
at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2538)
at picocli.CommandLine$RunAll.handle(CommandLine.java:2532)
at picocli.CommandLine$RunAll.handle(CommandLine.java:2492)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
at picocli.CommandLine$RunAll.execute(CommandLine.java:2494)
at picocli.CommandLine.execute(CommandLine.java:2170)
at de.maibornwolff.codecharta.tools.ccsh.Ccsh$Companion.executeCommandLine(Ccsh.kt:97)
at de.maibornwolff.codecharta.tools.ccsh.Ccsh$Companion.main(Ccsh.kt:87)
at de.maibornwolff.codecharta.tools.ccsh.Ccsh.main(Ccsh.kt)
```

## Steps to Reproduce the Problem

n/a

## Specifications

latest codecharta analysis tooling

i tried the process directly through the git log parser of the codecharta and the manual exporting of the git log.
the manual export of the git log prints this:

```
warning: exhaustive rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 4261 and retry the command.
```

**Comment by Nereboss** [comment] 2023-12-21 12:15
We were unfortunately not able to reproduce this issue with the given information. 
Could you give us some more information, for example the exact command that was executed to produce this error, or the complete error message (Part in actual behaviour seems to only include the stack trace, not the thrown error), or more information about the scanned repository?

**Comment by ce-bo** [comment] 2023-12-21 15:31
@MO2k4 If it is closed source, how old is the repository? We could try to parse a similar repo to reproduce this case.

**Comment by ChristianHuehn** [comment] 2024-04-12 15:00
As we cant reproduce this and waited for around 4 months we will close this. @MO2k4 if you ever get this problem again and can provide more information feel free to create a new issue

**Closed by ChristianHuehn** 2024-04-12 15:00 UTC
Labels: bug, pr-analysis, priority:high, difficulty:medium
