### ISSUE TITLE
Label improvements

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2454] opened 2021-10-18 07:40 UTC
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As an Auditor, I want to be more flexible on showing labels, so that important labels do not overlap in screenshots used for analysis reports or presentations. Example:

![image](https://user-images.githubusercontent.com/26900540/137689897-6f10636b-49e4-432d-85cf-4997782350f3.png)

## Acceptance criteria
- To be refined

## Open questions
- Should we be able to show a label for one specific node by implementing a new context menu option "activate label"? (Duplicate: #1234),
- Should we be able to move labels via drag and drop?
- Should we decrease the label size?

**Comment by BridgeAR** [comment] 2021-11-15 21:44
Closing as duplicate of https://github.com/MaibornWolff/codecharta/issues/334.

**Closed by BridgeAR** 2021-11-15 21:44 UTC
Labels: pr-visualization, javascript, feature
