### ISSUE TITLE
MergeFilter is too slow with big files

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#276] opened 2018-11-12 10:54 UTC
# Feature request

## Description

As I have talked to @ukinimod, we should really add the option to delete nodes from a cc.json file, because merging huge files takes much too long.

## Question
- Analysis: How could an analysis filter look like to input the nodepaths?
- Visualization: 
    - Do we gonna introduce another *hard deletion* `ExcludeType`, which is also stored in the blacklist to make the deletion repeatable on newer versions of the cc.json map (with another new analysis filter) or 
    - should we give the user the option to delete excluded nodes when downloading the code map file?

**Comment by ukinimod** [comment] 2018-11-19 19:08
@alschmut I'm a bit at a loss what the FR is about. 
For the mergefilter there is also the solution to use not the recursive node merging but the leaf node merging. Probably the former should be converted entirely in the later. The performance for the non-traversing strategy is much faster and was enough for my examples.

I still would propose to be able to do white and blacklisting of nodes using the backend as it fits better into my personal workflow. The use case I have in mind is, getting a c# codebase, there are certain generated files I always want to exclude (Reference.cs,...). Even when I get two snapshots of a codebase I want to include / exclude the same things in both cc.json. When I do this on the backend I am able to do this repeatably without additional manual effort. When I am able to do hard delete it speeds up every process including merging.

It works now, with a bit of additional manual effort, so for me the priority of the issue is rather low.

**Comment by Richargh** [comment] 2018-11-30 13:10
This relates to #181 which I closed too early.

**Comment by Richargh** [comment] 2019-06-24 06:53
@alexhunziker did #547 also improve the speed of the merge filter or why did you reference this issue?

**Comment by alexhunziker** [comment] 2019-06-24 09:12
I think @alschmut added this issue to the pull request of #547 since in the description of this issue it is suggested to address this by providing a hard-delete option, which the new filter does.

Regarding the actual speed of the merge-filter no measures were taken. So it depends wha the issue is actually about; if it is about the merge-filter being slow due to unnecessarily large .cc.json files then it is addressed, if it is about the actual speed of the merging it is not.

**Comment by Richargh** [comment] 2019-06-25 12:29
Works for me. Should we close this feature for now and see if we get different feedback?

**Closed** 2019-06-27 16:49 UTC
Labels: analysis, question, visualization
