### ISSUE TITLE
Event tracking doesn't work properly

### ISSUE THREAD

**Issue by Hall-Ma** [MaibornWolff/codecharta#2666] opened 2022-02-16 09:17 UTC
# Bug

## Actual Behavior

When opening CodeCharta Demo a console error appears.

## Screenshots
![image](https://user-images.githubusercontent.com/72517530/154227261-024f4fa6-b432-4da6-977c-b75600f5e0dc.png)

## Steps to Reproduce the Problem
- I can't reproduce this locally.
- In the demo the console error appears only when CodeCharta is loading for the first time

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.90.0
- OS: Windows
- Browser: Chrome

**Comment by BridgeAR** [comment] 2022-06-03 08:40
I could not reproduce this either. I am going to close this as already fixed. Please open a new issue in case you encounter this again.

**Closed by BridgeAR** 2022-06-03 08:40 UTC
Labels: bug, pr-visualization, priority:high
