### ISSUE TITLE
MetricGardener not working in container

### ISSUE THREAD

**Issue by moritz-suckow** [MaibornWolff/codecharta#3318] opened 2023-05-25 15:21 UTC
# Bug

## Expected Behavior

WHEN

I try to parse a project in my current working directory with MetricGardener in a docker container

THEN

I want that to generate a cc.json file.

## Actual Behavior

When trying to parse a project in my current working directory in a docker container with MetricGardener using the following command 
`docker run --name codecharta-analysis -it -v $(pwd):$(pwd) -w $(pwd) codecharta/codecharta-analysis ccsh metricgardenerimport /path/to/project/in/container -o testMetricGardener.cc.json`
I get an exception and no file is generated:

`Error: EACCES: permission denied, open '/tmp/MGOutput8715757456794394780.json`

I am not sure if this is a setup problem from my side or something else. If it is, we should probably expand the documentation to include more specific setup instructions!

**Comment by fritschldwg** [comment] 2023-12-18 10:27
I couldn't reproduce this on any of the following shells on Windows:
- CMD
- Powershell
- WSL2 - RancherDesktop

This seems related to docker not having the necessary permissions to access system resources on MacOS

`
docker run -it -v $(pwd):$(pwd) -w $(pwd) codecharta/codecharta-analysis /bin/bash  
`
`
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
`

`
root@1b5a8b57857d:/Users/niklaskneissl/Library/CloudStorage/OneDrive-MaibornWolffGmbH/IdeaProjects/codecharta# ls -l
`
`
ls: reading directory '.': Permission denied
total 0
`
`
root@1b5a8b57857d:/Users/niklaskneissl/Library/CloudStorage/OneDrive-MaibornWolffGmbH/IdeaProjects/codecharta# whoami
`
`
root
`

Will further debug this with @Nereboss

**Comment by Nereboss** [comment] 2023-12-19 16:27
Seems to be a permission issue caused by npm and folder privileges, as we found out [here](https://github.com/npm/cli/issues/5533). Upgrading to node v18 (npm v10) fixes this issue as npm no longer attempts to discover or change folder permissions from version 9.0.0.

Issue no longer appears when locally building the container with node v18, so upgrading node will solve this issue

**Comment by ce-bo** [comment] 2023-12-19 16:52
Let's upgrade node accordingly, so that this can be resolved.

**Comment by fritschldwg** [comment] 2024-03-20 11:10
@Nereboss, could you please test this again on your local setup? We've updated the Dockerfile to use Node v18, so this issue should now be resolvable without any additional steps.

**Comment by Nereboss** [comment] 2024-03-21 09:57
Tested this with a local build of the current main branch (that is updated to node 18). This will be fixed in the next analysis release, as that will include the upgrade to node 18, therefore we already close this issue

**Closed by Nereboss** 2024-03-21 09:57 UTC
Labels: bug, question, pr-analysis, priority:high, blocked
