### ISSUE TITLE
Improve buildings "Keep Highlighted" option

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1545] opened 2020-12-03 15:21 UTC
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As an user, I want to select multiple buildings using the "keep highlighted" option in the node context menu, so that I can highlight multiple buildings at the same time.

## Acceptance criteria
- On clicking the "Keep Highlighted" node context menu option of an unselected building the building should be selected (orange). This is not the case at the moment.
- If the second/third/n'th building is marked as "Keep Highlighted" mark it as an orange building as well.

![image](https://user-images.githubusercontent.com/26900540/101048657-1a1c9200-3583-11eb-99c0-87763d162146.png)
This might be a bug that a "keep-highlighted"-building is not orange (right click on unselected building > keep highlighted: nothing happens): ![image](https://user-images.githubusercontent.com/26900540/101048891-4d5f2100-3583-11eb-8af2-8ebd0f9bae25.png)

**Comment by BridgeAR** [comment] 2021-11-15 21:53
AFAIK it is possible to use the feature on multiple buildings and it does work as expected for me. The highlight color is not orange but just a different lighter building color.

I am going to close this as working as intended. If that's a mistake, please reopen.

**Closed by BridgeAR** 2021-11-15 21:53 UTC
Labels: pr-visualization, javascript, feature
