### ISSUE TITLE
Full delta for new Files not working

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#92] opened 2018-03-01 10:16 UTC
There was a nice feature that visualized new files completely green (or in some different color). I tested it on the current (1.9.3) version in Chrome and it didn't work for my data. Is this feature still activated?

**Comment by mrpatpat** [comment] 2018-03-01 17:54
Hi, 

this feature is still active and is working with the sample data. Steps to reproduce it: 

1. Load CC with the two default sample maps (Note: The deployed online demo uses other maps, simply build it locally)
2. Activate deltas.
3. Set the area metric to unary. Nodes which exist in only one map have a value of 0 for every metric but the unary metric. 
4. Choose in the "Maps" tab: show "sample1.json" in comparison to "sample2.json"
5. There should be a fully green node named "sample1 only leaf" with a height value of 100 and a height delta of a 100.

It would actually be better to visualize added/deleted nodes with a special, metric-less, symbol. This would make them always visible (not only with unary area) and create a clear distinction. Another problem is assuming that the metrics are 0. 0 is not a "non existant" value e.g. a new file would be very good in terms of "number of bugs".

**Comment by ukinimod** [comment] 2018-03-01 18:01
Is it necessary to use the unary metric? Or will it work, at least for added files with other metrics.

Ps on hindsight i dont think the distinction between newly added files is necessary. At least for metrics i am using. On the contrary, it would rather be distracting.

**Comment by ukinimod** [comment] 2018-03-02 20:34
The functionality is working fine with this deployed example, but it is not working with my actual projects. I tested this feature again using both the newest merged version and the newest version of the online demo:
- I opened two files (see attached files)
- I switched to delta view
- I selected unary as area metric
- I chose the 2- for the reference and 34- as comparison
It only showed files from the 2- version. Choosing 34 as reference and 2 as comparison showed only files in 34.

[2-codecharta-cloc.cc.txt](https://github.com/MaibornWolff/codecharta/files/1776487/2-codecharta-cloc.cc.txt)
[34-codecharta-cloc.cc.txt](https://github.com/MaibornWolff/codecharta/files/1776488/34-codecharta-cloc.cc.txt)

**Comment by mrpatpat** [comment] 2018-03-05 12:57
I can confirm that it is not working as expected for the given examples. I will dive into this issue as soon as possible since it is a critical functionality. I am currently finishing #91, #92 will be the next task.

**Comment by mrpatpat** [comment] 2018-03-05 17:24
Hi @ukinimod,
as far as I can see this is fixed in #98. Do you know the full expected result ? I just picked some values for the check but it would be nice if we could fully confirm it.

**Comment by ukinimod** [comment] 2018-03-05 20:03
Nice, @mrpatpat. I checked it. There are 4 nodes that are common to both versions, which is correct. There should be 34 deleted nodes and 141 added nodes. I didn't count them in the visualization but at a quick glance it seems right. In the following a list of the deltas.

I think we can close this issue if we could confirm the numbers of added and deleted files. Any idea how to do this without counting, @mrpatpat ?

common:
./analysis/tools/ValidationTool/src/main/kotlin/de/maibornwolff/codecharta/tools/validation/EveritValidator.kt
./analysis/tools/ValidationTool/src/main/kotlin/de/maibornwolff/codecharta/tools/validation/ValidationTool.kt
./analysis/tools/ValidationTool/src/main/kotlin/de/maibornwolff/codecharta/tools/validation/Validator.kt
./analysis/tools/ValidationTool/src/test/kotlin/de/maibornwolff/codecharta/tools/validation/EveritValidatorTest.kt

only 34:
./analysis/export/CSVExporter/src/main/kotlin/de/maibornwolff/codecharta/exporter/csv/CSVExporter.kt
./analysis/filter/MergeFilter/src/main/kotlin/de/maibornwolff/codecharta/filter/mergefilter/LeafNodeMergerStrategy.kt
./analysis/filter/MergeFilter/src/main/kotlin/de/maibornwolff/codecharta/filter/mergefilter/MergeException.kt
./analysis/filter/MergeFilter/src/main/kotlin/de/maibornwolff/codecharta/filter/mergefilter/MergeFilter.kt
./analysis/filter/MergeFilter/src/main/kotlin/de/maibornwolff/codecharta/filter/mergefilter/NodeMerger.kt
./analysis/filter/MergeFilter/src/main/kotlin/de/maibornwolff/codecharta/filter/mergefilter/NodeMergerStrategy.kt
./analysis/filter/MergeFilter/src/main/kotlin/de/maibornwolff/codecharta/filter/mergefilter/ProjectMerger.kt
./analysis/filter/MergeFilter/src/main/kotlin/de/maibornwolff/codecharta/filter/mergefilter/RecursiveNodeMergerStrategy.kt
./analysis/filter/MergeFilter/src/test/kotlin/de/maibornwolff/codecharta/filter/mergefilter/LeafNodeMergerTest.kt
./analysis/filter/MergeFilter/src/test/kotlin/de/maibornwolff/codecharta/filter/mergefilter/NodeMergerTest.kt
./analysis/filter/MergeFilter/src/test/kotlin/de/maibornwolff/codecharta/filter/mergefilter/ProjectMergerTest.kt
./analysis/filter/MergeFilter/src/test/kotlin/de/maibornwolff/codecharta/filter/mergefilter/RecursiveNodeMergerTest.kt
./analysis/import/CSVImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/csv/CSVHeader.kt
./analysis/import/CSVImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/csv/CSVImporter.kt
./analysis/import/CSVImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/csv/CSVProjectAdapter.kt
./analysis/import/CSVImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/csv/CSVRow.kt
./analysis/import/CSVImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/csv/SourceMonitorImporter.kt
./analysis/import/CSVImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/csv/CSVHeaderTest.kt
./analysis/import/CSVImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/csv/CSVProjectAdapterTest.kt
./analysis/import/CSVImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/csv/CSVRowTest.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/InputFormatNames.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/SCMLogParser.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/SCMLogProjectCreator.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/converter/ProjectConverter.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/Commit.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/Modification.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/VersionControlledFile.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/AbsoluteCodeChurn.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/AbsoluteCoupledChurn.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/AddQuotDel.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/AverageCodeChurnPerCommit.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/CalendarWeek.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/HighlyCoupledFiles.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/LinesOfCode.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/MedianCoupledFiles.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/Metric.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/MetricsFactory.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/NumberOfAuthors.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/NumberOfOccurencesInCommits.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/RangeOfWeeksWithCommits.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/RelativeCodeChurn.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/SuccessiveWeeksWithCommits.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/WeeksWithCommits.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/CommitCollector.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/LogLineCollector.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/LogLineParser.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/LogParserStrategy.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/AuthorParser.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/CommitDateParser.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/GitLogNumstatParserStrategy.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/GitLogNumstatRawParserStrategy.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/GitLogParserStrategy.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/GitLogRawParserStrategy.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/Status.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/svn/SVNLogParserStrategy.kt
./analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/svn/Status.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/SCMLogProjectCreatorGoldenMasterTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/SCMLogProjectCreatorTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/converter/ProjectConverterTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/VersionControlledFileTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/AbsoluteCodeChurnTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/AbsoluteCoupledChurnTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/AddQuotDelTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/AverageCodeChurnPerCommitTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/CalendarWeekTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/HighlyCoupledFilesTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/LinesOfCodeTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/MedianCoupledFilesTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/MetricsFactoryTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/NumberOfAuthorsTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/NumberOfOccurencesInCommitsTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/RangeOfWeeksWithCommitsTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/RelativeCodeChurnTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/SuccessiveWeeksWithCommitsTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/input/metrics/WeeksWithCommitsTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/CommitCollectorTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/LogLineCollectorTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/LogLineParserTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/ParserStrategyContractTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/AuthorParserTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/CommitDateParserTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/GitLogNumstatParserStrategyRenamingTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/GitLogNumstatParserStrategyTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/GitLogNumstatRawParserStrategyTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/GitLogParserStrategyTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/GitLogRawParserStrategyTest.kt
./analysis/import/SCMLogParser/src/test/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/svn/SVNLogParserStrategyTest.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarCodeURLLinker.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarComponentProjectAdapter.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarImporterException.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarImporterMain.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarMeasuresAPIImporter.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarMetricTranslatorFactory.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/dataaccess/AuthentificationHandler.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/dataaccess/GsonProvider.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/dataaccess/SonarMeasuresAPIDatasource.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/dataaccess/SonarMetricsAPIDatasource.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/filter/ErrorResponseFilter.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/model/Component.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/model/ComponentMap.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/model/ErrorEntity.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/model/ErrorResponse.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/model/Measure.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/model/Measures.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/model/MetricObject.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/model/Metrics.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/model/PagingInfo.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/model/Qualifier.kt
./analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/model/Scope.kt
./analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarCodeURLLinkerTest.kt
./analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarComponentProjectAdapterTest.kt
./analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarMeasuresAPIImporterTest.kt
./analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/dataaccess/AuthentificationHandlerTest.kt
./analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/dataaccess/SonarMeasuresAPIDatasourceIntegrationTest.kt
./analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/dataaccess/SonarMetricsAPIDatasourceIntegrationTest.kt
./analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/filter/ErrorResponseFilterTest.kt
./analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/Node.kt
./analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/NodeType.kt
./analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/Path.kt
./analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/PathFactory.kt
./analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/Project.kt
./analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/Tree.kt
./analysis/model/src/main/kotlin/de/maibornwolff/codecharta/nodeinserter/NodeInserter.kt
./analysis/model/src/main/kotlin/de/maibornwolff/codecharta/serialization/NodeJsonDeserializer.kt
./analysis/model/src/main/kotlin/de/maibornwolff/codecharta/serialization/ProjectDeserializer.kt
./analysis/model/src/main/kotlin/de/maibornwolff/codecharta/serialization/ProjectSerializer.kt
./analysis/model/src/main/kotlin/de/maibornwolff/codecharta/translator/MetricNameTranslator.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/model/NodeMatcher.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/model/NodeTest.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/model/PathFactoryTest.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/model/PathMatcher.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/model/PathTest.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/model/ProjectMatcher.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/model/TreeCreator.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/model/TreeTest.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/nodeinserter/NodeInserterTest.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/serialization/NodeJsonDeserializerTest.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/serialization/ProjectDeserializerTest.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/serialization/ProjectSerializerTest.kt
./analysis/model/src/test/kotlin/de/maibornwolff/codecharta/translator/MetricNameTranslatorTest.kt
./analysis/tools/ccsh/src/main/kotlin/de/maibornwolff/codecharta/tools/ccsh/Ccsh.kt

only 2:
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/SonarImporterException.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/SonarImporterMain.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/SonarImporterParameter.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/SonarReader.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/SonarResourceToProjectConverter.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/SonarXMLImport.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/dataaccess/AuthentificationHandler.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/dataaccess/SonarRESTDatasource.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/model/MetricObject.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/model/Metrics.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/model/Qualifier.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/model/Scope.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/model/SonarAttribute.java
./analysis/import/SonarImporter/src/main/java/de/maibornwolff/codecharta/importer/sonar/model/SonarResource.java
./analysis/import/SonarImporter/src/test/java/de/maibornwolff/codecharta/importer/sonar/SonarReaderTest.java
./analysis/import/SonarImporter/src/test/java/de/maibornwolff/codecharta/importer/sonar/SonarResourceToProjectConverterTest.java
./analysis/import/SonarImporter/src/test/java/de/maibornwolff/codecharta/importer/sonar/SonarXMLImporterTest.java
./analysis/import/SonarImporter/src/test/java/de/maibornwolff/codecharta/importer/sonar/dataaccess/AuthentificationHandlerTest.java
./analysis/import/SonarImporter/src/test/java/de/maibornwolff/codecharta/importer/sonar/dataaccess/SonarRESTDatasourceIntegrationTest.java
./analysis/import/SonarImporter/src/test/java/de/maibornwolff/codecharta/importer/sonar/dataaccess/SonarRESTDatasourceTest.java
./analysis/model/src/main/java/de/maibornwolff/codecharta/model/Node.java
./analysis/model/src/main/java/de/maibornwolff/codecharta/model/NodeType.java
./analysis/model/src/main/java/de/maibornwolff/codecharta/model/Path.java
./analysis/model/src/main/java/de/maibornwolff/codecharta/model/Project.java
./analysis/model/src/main/java/de/maibornwolff/codecharta/nodeinserter/FileSystemPath.java
./analysis/model/src/main/java/de/maibornwolff/codecharta/nodeinserter/NodeInserter.java
./analysis/model/src/main/java/de/maibornwolff/codecharta/serialization/NodeJsonDeserializer.java
./analysis/model/src/main/java/de/maibornwolff/codecharta/serialization/ProjectDeserializer.java
./analysis/model/src/main/java/de/maibornwolff/codecharta/serialization/ProjectSerializer.java
./analysis/model/src/test/java/de/maibornwolff/codecharta/nodeinserter/FileSystemPathTest.java
./analysis/model/src/test/java/de/maibornwolff/codecharta/nodeinserter/NodeInserterTest.java
./analysis/model/src/test/java/de/maibornwolff/codecharta/serialization/NodeJsonDeserializerTest.java
./analysis/model/src/test/java/de/maibornwolff/codecharta/serialization/ProjectDeserializerTest.java
./analysis/model/src/test/java/de/maibornwolff/codecharta/serialization/ProjectSerializerTest.java

**Comment by mrpatpat** [comment] 2018-03-08 08:14
I logged all the different counts while comparing the maps and the numbers add up to the ones provided by you. Although this issue seems to be closed, I would prefer to design some meaningful e2e tests which provide two json files and compare against an expected one. It should be possible to programmatically search a directory for json file triplets and then use them in the test. I will change the label on this issue.

**Closed** 2018-03-27 10:40 UTC
Labels: enhancement, visualization
