### ISSUE TITLE
Metric Scenario chosen should be displayed as long as it's valid

### ISSUE THREAD

**Issue by alexhunziker** [MaibornWolff/codecharta#585] opened 2019-06-21 07:59 UTC
# Feature request

## Description

When choosing a Scenario from the dropdown menu, the metrics are adjusted accordingly. However, the dropdown menu becomes blank immediatly after selecting an entry (see screenshot)
![grafik.png](https://images.zenhubusercontent.com/5cd917d44fc7730780f8533f/8fe1d811-186a-4927-8455-22387f79a4cc)

It would be nice, if the metric scenario would be displayed in this dropdown, as long as it corresponds to the metrics active for height/color/area.
![grafik.png](https://images.zenhubusercontent.com/5cd917d44fc7730780f8533f/8b1436e6-26e9-48e3-84cb-5ccedc6724d8)

**Comment by NearW** [comment] 2019-07-19 11:00
#641 is a duplicate of this

**Comment by alschmut** [comment] 2019-07-26 07:45
We'll close this issue its obsolete by #628

**Closed by alschmut** 2019-07-26 07:45 UTC
Labels: visualization
