### ISSUE TITLE
ccsh argument inconsistency

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#772] opened 2019-11-08 11:22 UTC
# Feature request

## Description

The argument description is inconsistent. Sometimes it says --projectName and sometimes --project-name.
We should agree on camelCase or kebab-case.

**Comment by alexhunziker** [comment] 2019-11-08 11:28
This may be off-topic but: Speaking of the projectName.... in the analysis we pretend that this attribute is super important (by default the merging of two project fails if the names are not matching for example) but in the visualization we do almost/absolutely nothing with this attribute. 

Therefore the question: What is the purpose of this field? If there is none, let's remove it. If there is one, we might want to show the project name in the visualization as well.

**Comment by alschmut** [comment] 2019-11-08 14:44
I have actually been asking this question to myself since I am part of CodeCharta and I would say the original reason to introduce it, was to avoid the merge of two different projects. But to be honest the projectName is not always set correctly and depends (if I am right) mostly on the importer. I think we can evaluate if files should be merged or not without administrating the projectName, simply by comparing some of the top nodes in the cc.json map.
- If the top nodes seems to be mostly identical, we can merge it
- If they don't we could abort and suggest to double check the files with the structure modifier

**Comment by alexhunziker** [comment] 2019-11-08 15:33
Yes, you are right, if the projectName is not set manually, it depends on the importer (i guess with the exception of the SonarImporter). With #567 we have introduced Log messages, which inform the user to what degree the merged projects were matching up. This is in my opinion enough information to the user so that he can see if the  merge yielded the desired result or not. 

If there is no other purpose of the projectName I say let's remove it completely.

**Comment by alschmut** [comment] 2020-01-06 17:28
Are there any new thoughts on this issue? I am actually really excited to have this cleaned up 😃

**Comment by alexhunziker** [comment] 2020-01-07 11:52
When cleaning up the arguments, i suggest that in the SCMLogParser we remove the --git and --svn arguments, and instead always ask for the input format. 

Why? First --git does nothing else than set --input-format to GIT_LOG and second GIT_LOG is just one of the candidates for a git log file and may not be appropriate. If both arguments are set, the --input-format is ignored. So if you do somehting along the lines of `ccsh scmlogparser foo.log --git --input-format=GIT_LOG_NUMSTAT_RAW` the parser will discard GIT_LOG_NUMSTAT_RAW and instead use GIT_LOG, which is unexpected behaviour in my opinion. Therefore i suggest removing --git and --svn altogether. That way the interface becomes more understandable.

**Comment by alschmut** [comment] 2020-01-07 17:24
@alexhunziker I agree with removing the simplified `--git` and `--svn` parameters

but, I think this issue was about the projectName wasn't it? ;)

**Comment by alschmut** [comment] 2020-01-24 11:32
I think we should also remove the projectName inside our visualisation:
- Remove reading it into our CCFile's
- Not exporting it when downloading the current map

What do you think about that?

**Closed** 2020-01-29 19:29 UTC
Labels: pr-analysis, question
