### ISSUE TITLE
Adjust number of labels to be displayed by keyboard/mouse is not possible

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1270] opened 2020-09-18 12:53 UTC
# Bug
Clicking the input field (within height overlay) for the number of displayed labels will close the overlay and I cannot enter the number by keyboard.

## Expected Behavior

GIVEN
Opened height overlay

WHEN
Clicking the up/down arrow or inside the input field itself

THEN
The overlay remains open, so that I can enter the number of displayed labels by keyboard or click mutlitple times up/down arrow

## Actual Behavior
The overlay is closed on the first click instead.

## Screenshots
![cc-bug-height-labels-input](https://user-images.githubusercontent.com/26900540/93599396-5e55b880-f9be-11ea-90d3-3d0503b31ca0.PNG)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes

**Comment by BridgeAR** [comment] 2020-09-18 12:59
This should be a duplicate

**Comment by NearW** [comment] 2020-09-24 11:18
Was a duplicate of #1258. I'll close this.

**Closed by NearW** 2020-09-24 11:18 UTC
Labels: bug, pr-visualization, priority:urgent
