### ISSUE TITLE
Add Importer for semantic

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#556] opened 2019-06-05 07:59 UTC
# Feature request

Add an importer for the command-line tool [semantic](https://github.com/github/semantic/blob/master/README.md)

**Comment by BridgeAR** [comment] 2021-11-15 19:41
@ce-bo is currently implementing a parser using [tree-sitter](https://tree-sitter.github.io/tree-sitter/). It supports more languages and is easier to use.

**Comment by BridgeAR** [comment] 2021-11-15 21:47
Closing as duplicate of #1885

**Closed by BridgeAR** 2021-11-15 21:47 UTC
Labels: pr-analysis, feature, priority:urgent
