### ISSUE TITLE
TypeError: Cannot read property 'getCenterPoint' of undefined

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1033] opened 2020-07-04 12:00 UTC
# Bug

## Expected Behavior

GIVEN an open map in presenter mode

WHEN hovering over the file percentages (the part next to metrics)

![image](https://user-images.githubusercontent.com/8822573/86512022-9bb69b00-bdfe-11ea-8664-d6f1474168c7.png)

THEN a TypeError is triggered

## Actual Behavior

```
TypeError: Cannot read property 'getCenterPoint' of undefined
    at CodeMapMesh.adjustSurroundingBuildingColors (codeMapMesh.ts:98)
    at codeMapMesh.ts:87
    at Array.forEach (<anonymous>)
    at CodeMapMesh.highlightBuilding (codeMapMesh.ts:82)
    at ThreeSceneService.highlightBuildings (threeSceneService.ts:61)
    at ThreeSceneService.selectBuilding (threeSceneService.ts:85)
    at ThreeSceneService.reselectBuilding (threeSceneService.ts:176)
    at ThreeSceneService.onRenderMapChanged (threeSceneService.ts:56)
    at codeMap.preRender.service.ts:202
    at Scope.$broadcast (angular.js:19788)
```

## Specifications

- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.1
- OS: Ubuntu 20.04
- Browser: Chromium

**Comment by ce-bo** [comment] 2020-10-21 08:00
This seems to be fixed.
I could not repreduce the TypeError.

**Comment by BridgeAR** [comment] 2020-10-21 08:08
Still there:

![image](https://user-images.githubusercontent.com/8822573/96691599-5e622300-1385-11eb-811e-2f7594f58b87.png)

**Comment by ce-bo** [comment] 2020-10-21 08:30
This error does not occur in every map.
I can reproduce the error now, using the map of CodeCharta web demo.

**Comment by ce-bo** [comment] 2020-10-21 11:59
First impression: The error occurs when hovering a distribution like "Other". It seems that the map has no files/buildings rendered for this distribution. The implementation for this case is broken.

**Comment by RomanenkoVladimir** [comment] 2021-01-15 10:08
I tried to reproduce the bug on different maps, but could not do it.
@BridgeAR @ce-bo: Could you please check again/ link a map that produces the error?

**Comment by BridgeAR** [comment] 2021-01-15 11:16
Interesting. I can't reproduce it either anymore (@ce-bo are you still able to trigger it?). We might have fixed it with something else. I wonder if it's possible to write a regression test for it.

**Comment by ce-bo** [comment] 2021-01-22 08:54
Hmm. I can't reproduce it anymore because in the web demo the "Other" distribution isn't shown anymore. I tested some other maps - one with a "other" distribution. Everything seems to be fine.

**Comment by JaiJoPa** [comment] 2021-02-19 10:31
We could not reproduce the error anymore. So closing this issue.

**Closed by JaiJoPa** 2021-02-19 10:31 UTC
Labels: bug, pr-visualization, priority:high
